### ISSUE TITLE
Design the landing page feature.

### ISSUE THREAD

**Issue by sieupot** [sieupot/sieupot.github.io#1]
This is the first thing the user sees when accessing the app, the starting point of his journey, the path he decides to walk for his current session.

**Comment by dan20071** [comment]
Salut, am inceput sa lucrez la partea de splash screen, adica selectia nivelurilor si a activitatilor. O sa adaug aici ce am ca sa putem discuta maine.

![SiEuPot V1 0 Nivelul 1](https://user-images.githubusercontent.com/78590871/111986456-a644cc00-8b16-11eb-8cc1-85ecaffb5632.png)
![SiEuPot V1 0 Landing](https://user-images.githubusercontent.com/78590871/111986460-a6dd6280-8b16-11eb-8249-07457f993dbe.png)

**Comment by dan20071** [comment]
Avem si un link interactiv cu paginile astea 2 aici: https://xd.adobe.com/view/70deaee0-398f-4e44-9508-0d8353d8dd6a-258d/?fullscreen

**Comment by tgtn** [comment]
Wow!!! Looking good!!!!!!
Zici ca e aplicatie adevarata, nu fake-ul ala inceput de mine :D

Teodor GUTAN
Tel: +40.721.43.82.83
E-mail: ***@***.***
